"""
Global declarations of urls so that they can be used anywhere by importing the config file
"""
MOST_ACTIVE_STOCKS_URL = "https://in.finance.yahoo.com/most-active"
MOST_ACTIVE_STOCKS_URL_50 = "https://in.finance.yahoo.com/most-active?offset=0&count=50"
MUTUAL_FUNDS_URL = "https://in.finance.yahoo.com/mutualfunds"
CURRENCIES_URL = "https://in.finance.yahoo.com/currencies"
CRYPTOCURRENCIES_URL = "https://in.finance.yahoo.com/cryptocurrencies"
STOCK_GAINERS_URL = "https://in.finance.yahoo.com/gainers"
STOCK_LOSERS_URL = "https://in.finance.yahoo.com/losers"